### ISSUE TITLE
Does not serialize nested properties

### ISSUE THREAD

**Issue by Danika1808** [neuroglia-io/asyncapi#14]
## Description
Does not serialize nested reference properties

## How to reproduce?
I tryed to serialize any model with nested reference properties

## Expected behavior
nested reference properties has description

## Actual behavior
nested referenece type has None description
![image](https://user-images.githubusercontent.com/65758418/197509378-5c5e19ce-dcfd-46c2-b305-724b69fa48e4.png)
## Additional info
I think this is trouble with MaxDepth setting of JsonSerializer

**Comment by cdavernas** [comment]
Hi @Danika1808 and sorry for the delay, this year has been crazy for me.

I am currently working on a NET8 refactor, this should not occur anymore.

Will keep you posted
