### ISSUE TITLE
Feature: Support code-first generation in Azure Function Apps

### ISSUE THREAD

**Issue by NattyMojo** [neuroglia-io/asyncapi#15]
## Description
Support for code-first generation in Azure Function Apps. The implementation seems to rely on MVC middleware, which is not available in Azure Functions. Need a way to generate AsyncApi documents using the attributes in code and view in running app. I use event-driven architecture with Azure Functions, and I'm sure many others do the same. So is this possible in the package today? Or has it been thought of as an addition?

## Alternatives
Tried Saunter and opened relevant ticket [152](https://github.com/tehmantra/saunter/issues/152) and KsntServiceBus and opened relevant ticket [12](https://github.com/d0972058277/KnstEventBus/issues/12)

Opened question on [StackOverflow](https://stackoverflow.com/q/74774670/11326702) for alternate suggestions

**Comment by cdavernas** [comment]
@NattyMojo The NET8 refactor has been published, and now provides a new [Neuroglia.AsyncApi.DependencyInjectionExtensions](https://www.nuget.org/packages/Neuroglia.AsyncApi.DependencyInjectionExtensions) package, which is completely indepent from the web SDK.

## Usage:

*Configuration:*

```cs
services.AddAsyncApiGeneration(builder =>
    builder.WithMarkupType<StreetLightsService>());
```

*Retrieve generated documents:*

```cs
var documentList = serviceProvider.GetRequiredService<IAsyncApiDocumentProvider>().ToList();
```

*Add a document manually:*

```cs
services.AddAsyncApiDocument(myDocument);
```

OR:

```cs
services.AddAsyncApiDocument(builder => builder
  .WithAsyncApiVersion(...)
  ...);
```

Hope this addresses your use case! If it does not, don't hesitate to reopen the issue!
