### ISSUE TITLE
Feature: Choose which classes should be included in the YML definition

### ISSUE THREAD

**Issue by Krusty93** [neuroglia-io/asyncapi#17]
## Description
It would be possible to choose which classes should be included in the YML/Json generated file via a selector rather than attributes?

Applying the SDK's custom attributes on existing code makes really difficult the adoption of this framework. It would help to keep your code base agnostics from any external framework.

## Alternatives
Not applicable

### Example
From
```csharp
[Message(..)]
public class Event 
{
}
```
To:

```csharp
..
.UseMessage(message => message..., "namespace/anything else")
```

**Comment by cdavernas** [comment]
I'm gonna assume it does. Please reopen if need be ;)
