### ISSUE TITLE
BUG: The 'asyncapi' field does not match to the specification

### ISSUE THREAD

**Issue by BeardVis** [neuroglia-io/asyncapi#23]
## Description
The current version of Neuroglia.AsyncApi.Generation creates an asyncApi specification with 'asyncApi' field name in camelCase.
[Specification](https://github.com/asyncapi/spec/blob/master/spec/asyncapi.md#format) says:

> All field names in the specification are case sensitive.

Also in the [specification](https://github.com/asyncapi/spec/blob/master/spec/asyncapi.md#format) 'asyncapi' field name is specified in lower-case.

This issue causes plug-ins and asyncApi viewers to be unable to open the specification file generated by the current solution.

## How to reproduce?
Just generate an asyncApi by using Neuroglia.AsyncApi.Generation.

## Expected behavior
asyncapi field name specified in lower-case

## Actual behavior
asyncApi field name specified in camel-case

**Comment by cdavernas** [comment]
Hi @BeardVis and thanks for reporting! 
Adding that to my todo! If that's urgent for you, feel free to submit a PR instead 😉
