### ISSUE TITLE
BUG: `UseAsyncApiGeneration` Doesn't exist anymore

### ISSUE THREAD

**Issue by fdw** [neuroglia-io/asyncapi#35]
## Description
I'd like to call `UseAsyncApiGeneration()` on an `IApplicationBuilder`, just like the [readme](https://github.com/neuroglia-io/asyncapi/blob/main/README.md) says. However, there is no such extension method.

It seems it's now called `MapAsyncApiDocuments`

## How to reproduce?
1. Try to implement the example from the readme.
2. Be notified that `UseAsyncApiDocuments()` can't be found.

## Expected behavior
Either `UseAsyncApiGeneration` can be found again or the readme is updated.

## Actual behavior
The compiler is quite unhappy with me.

**Comment by cdavernas** [comment]
Closed by #36
