### ISSUE TITLE
Bug: Setting `PathPrefix` breaks the `AsyncApiGenerationMiddleware`

### ISSUE THREAD

**Issue by cdavernas** [neuroglia-io/AsyncApi#5]
## How to reproduce?

Set the `PathPrefix` when configuring AsyncAPI document generation, like so:

```csharp
...
services.AddAsyncApiGeneration(options =>
            {
                options
                .WithMarkupType<WeatherForecastController>()
                //.UsePathPrefix("/") Unquoting this line break the middleware
                .UseDefaultConfiguration(asyncapi =>
                {
                    asyncapi.UseServer("WebSocket", server => server
                        .WithUrl(new Uri("http://127.0.0.1:8081/ws/weather"))
                        .WithProtocol(AsyncApiProtocols.Ws)
                        .UseBinding(new WsServerBinding())
                        );
                });
            });
...
```

## Expected behavior

Documents are served with the configured path prefix

## Additional information

Fix the way the `PathPrefix` is used to allow both url document discovery and customized document urls

**Comment by smarek** [comment]
While you're at it, maybe properly handling all URLs in prefix, that do not result in correct endpoint, would be desired?
Such as `http://localhost:5000/AsyncApi/` results in similar AsyncApiGenerationMiddleware error (eg. adding slash `/` at the end of URL)

**Comment by smarek** [comment]
Also I'm struggling to get the UI working with different project, that is far more complex than the example i've provided today.
But, I found out, that changing the prefix, in that particular project, will turn the `/asyncapi => HTTP 404` into `/asyncapi => HTTP 500`, so there is definitely something worth looking into in the routing

with changed prefix, the stacktrace looks like this:
```
IndexOutOfRangeException: Index was outside the bounds of the array.
Neuroglia.AsyncApi.Middlewares.AsyncApiGenerationMiddleware.InvokeAsync(HttpContext context)
Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

without changed prefix, the only thing I get is the log in Host console like this
```
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 GET http://localhost:8080/asyncapi - - - 404 0 - 1.7869ms
```

Could you maybe let me know, if there is any way to check what routes did the `AddAsyncApiUI` call result into?

**Comment by cdavernas** [comment]
@smarek The problem, which was not documented anywhere, was due to the fact that the `prefix` should never be used alone in the path, as it points to the root of all available Async Api documents.

The following rules now apply:

- `/{prefix}`: displays a list of all available documents and their respective versions
- `/{prefix}/[documentTitle]`: displays a list of all versions for the specified document
- `/{prefix}/[documentTitle]/[documentVersion]`: displays the specified document, in YAML or JSON

Hope this solves your problems 😉

**Comment by smarek** [comment]
Perfect, thank you very much.
