### ISSUE TITLE
Usage when project target is Microsoft.NET.Sdk instead of Microsoft.NET.Sdk.Web

### ISSUE THREAD

**Issue by smarek** [neuroglia-io/asyncapi#6]
Hey @cdavernas , I finally pinpointed the issue I was struggling in my other project, which was the reason behind #3 

I've managed to reproduce, with the same project you've already seen, i've just removed swagger and the PathPrefix that will get addressed in #5 but changing the target SDK

See latest commit https://github.com/smarek/signalr-asyncapi-example/commit/975c64ec5f684a328c15e049056f5f9a44b7d174#diff-baf4e63ed3f9283edfde3518c8b1f4acb9ada87dd874db4e67fb1071a2239fd2R1

With this SDK target routes for individual spec documents work, but the default route for UI does not.

Could you please take a look, and let me know, if you can/will support this SDK target or mention in documentation that Microsoft.NET.Sdk.Web is required? Thank you!

**Comment by cdavernas** [comment]
@smarek Thanks for your input and investigation! I'll get back to it in a dozen days, for I just left for holidays. 
I'll ping you asap, and will fix the different bugs we are facing!

**Comment by cdavernas** [comment]
@smarek Can you please help me understand your goal? I'm a bit confused about that issue...
AFAIK, if you want to run an WebHost, you do need the `Microsoft.NET.Sdk.Web`, right? 
I imagine you could do it using the `Microsoft.NET.Sdk` only, and reference legacy .NET Standard 2.0 packages for ASP, but that wouldn't make too much sense to me having an app running on the latest framework version and being restricted by outdated libraries.

**Comment by smarek** [comment]
@cdavernas thank you, well i did not know it's not possible and i did it. Project with `Microsoft.NET.Sdk` using `<TargetFramework>net5.0</TargetFramework>` allowed me to use the usual aspnet.core IHostBuilder and run multiple WebHosts. In `dotnet list package` i see the `Swashbuckle.AspNetCore v6.1.4` and i went with the guide https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-5.0&tabs=visual-studio with single difference, that for whatever reason my project was at a time initialized with the `Microsoft.NET.Sdk`, not the `Sdk.Web` one.

Per docs, https://docs.microsoft.com/en-us/dotnet/core/project-sdk/overview
The `Microsoft.NET.Sdk` and `Microsoft.NET.Sdk.Web` differ only in pre-sets, where in `Microsoft.NET.Sdk.Web` it's easier to run web applications (different build/exec directory) and serve static/razor content. So I see no reason, why I should not use the dotnet5.0 WebHost without `Microsoft.NET.Sdk.Web` sdk target

**Comment by cdavernas** [comment]
@smarek In the end, do you need me to try avoiding explicit ref to `Microsoft.NET.Sdk.Web` or is it ok for you as is?

**Comment by smarek** [comment]
@cdavernas that is not the issue, i think, whatever SDK pre-set you're building on should not matter in fact?

The issue is that using your published packages from project not based on web-presets sdk, will fail to render the razor web interface. As I wrote in the issue opening comment, try download and run the sample project https://github.com/smarek/signalr-asyncapi-example and you should see that the `/asyncapi` route (without using `UsePathPrefix`) will fail to render the web-ui.

So it either should be declared, that you support only projects based on `.Sdk.Web` or it should be investigated, why it currently does not work in the sample project.

**Comment by cdavernas** [comment]
@smarek Allright, will check what's happening 😉

**Comment by smarek** [comment]
Thank you very much :-)

**Comment by cdavernas** [comment]
@smarek So, I tried to replace the SKD, which requires importing a couple of .NET CORE/.NET STANDARD packages and two or three minor fixes. One of those is replacing the code in [IAsyncApiUIServiceCollectionExtensions](https://github.com/neuroglia-io/AsyncApi/blob/main/src/Neuroglia.AsyncApi.AspNetCore.UI/Extensions/IAsyncApiUIServiceCollectionExtensions.cs) with the following:

```c#
...
services.AddMvcCore()
  .AddRazorPages(options =>
    if(!path.Equals("AsyncApi", StringComparison.OrdinalIgnoreCase))
      options.Conventions.AddPageRoute("/AsyncApi", path);
  )
...
```

Everything compiles as it should, but the UI page is not rendered anymore, as the .NET5.0's [MvcServiceCollectionExtensions](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.mvcservicecollectionextensions.addrazorpages?view=aspnetcore-5.0) seems to be using another implementation, defined in `
Microsoft.AspNetCore.App.Ref v5.0.0`.

So, in the end, it looks like the UI has an unresolvable dependency on `Sdk.Web` indeed: either I make the said fix, and it only works for .NET 5.0 projects without web ref (or projects running on .NET CORE 2.X or higher), or vice versa 😞

**Comment by smarek** [comment]
Welp bad luck then, thank you though for investigating, i've tried to find whether there is conditional based on target project sdk, but did not find anything useful.

So i suggest we don't need to create multiple builds/framework-targets, and just writing a warning to documentation/readme of this project, that it requires and works only with "Microsoft.NET.Sdk.Web" sdk, should suffice.

And btw, if you could think of any way, the necessary changes (to get it working with non-web sdk) could be done by project importing your AsyncApi/UI, instead of by changes in core of this project, i'd welcome that, but if nothing comes to mind, just close this issue, and thank you very much!
