### ISSUE TITLE
BUG: Parsing failing with simple example as soon as it hits schema "properties" of an "object"

### ISSUE THREAD

**Issue by BuzzyLizzy** [neuroglia-io/AsyncApi#9]
## Description
When the parsing hits the "properties" of the first "object" in a schema it hthrows an exception.

## How to reproduce?
I used the yaml example I got from the AsyncApi website that I supply in "Additional Info" below.
I created code in C# .Net Core 5 to parse it using AsyncApiDocumentReader.ReadAsync(..)

## Expected behavior
It should not fail, this AsyncApi yaml example is valid.

## Actual behavior
It fails on line 36 at the first "properties". If I delete everything from the first "properties" then it succeeds.
This is the error returned:
"Error: (Line: 36, Col: 7, Idx: 809) - (Line: 36, Col: 7, Idx: 809): Exception during deserialization"

## Additional info
Get the example here: https://www.asyncapi.com/blog/understanding-asyncapis
Or this is it:
```
asyncapi: 2.0.0
info:
  title: Email Service
  version: '1.0.0'
  description: |
    Sends emails upon certain events
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0

servers:
  production:
    url: mqtt://test.mosquitto.org
    protocol: mqtt
    description: Test MQTT broker

channels:
  user/signedup:
    publish:
      operationId: onUserSignUp
      message:
        $ref : '#/components/messages/UserSignedUp'

components:
  messages:
    UserSignedUp:
      name: userSignedUp
      title: User signed up event
      summary: Inform about a new user registration in the system
      contentType: application/json
      payload:
        $ref: '#/components/schemas/userSignedUpPayload'

  schemas:
    userSignedUpPayload:
      type: object
      properties:
        firstName:
          type: string
          description: "foo"
        lastName:
          type: string
          description: "bar"
        email:
          type: string
          format: email
          description: "baz"
        createdAt:
          type: string
          format: date-time
          description: "foo"
```

**Comment by cdavernas** [comment]
@BuzzyLizzy Thanks for the bug report. It is due to the YamlDotNetDeserializer trying to set a read-only property (`JSchema.Properties`). I'll have to come up with a custom JSchema deserializer.

**Comment by cdavernas** [comment]
@BuzzyLizzy This should have been fixed ;) Don't hesitate to reopen if that's not the case!
